### ISSUE TITLE
Planned Functionality and Implementation Status

### ISSUE THREAD

**Issue by 5310** [Hashfyre/pyzure-cli#1]
- [ ] `account`
  - Commands to manage your account information and publish settings.
  - [ ] `affinity-group`
    - Manage your Affinity Groups.
    - [ ] `create [options] <name>`
    - [ ] `delete [options] <name>`
    - [ ] `list [options]`
    - [ ] `show [options] <name>`
  - [ ]  `cert export [options]`
    - Export your account certificates.
  - [ ] `env`
    - Manage your account environment.
    - [ ] `add [options] [environment]`
    - [ ] `delete [options] [environment]`
    - [ ] `list [options]`
    - [ ] `set [options] [environment]`
    - [ ] `show [options] [environment]`
  - [ ] `clear [options]`
    - Remove a subscription or environment, or clear all of the stored account and environment info.
  - [ ] `download [options]`
    - Launch a browser to download your publishsettings file.
  - [ ] `import [options] <file>`
    - Import a publishsettings file or certificate for your account.
  - [ ] `list [options]`
    - List the imported subscriptions.
  - [ ] `set [options] <subscriptionNameOrId>`
    - Set the current subscription
  - [ ] `show [options] [subscriptionNameOrId]`
    - Show details about a subscription.
- [ ] `config`
  - Manage your local settings.
  - [ ] `config list [options]`
    - List config settings
  - [ ] `config delete [options] <name>`
    - Delete a config setting
  - [ ] `config mode [options] <name>`
    - Sets the cli working mode. 
    - Valid names are `arm` for resource manager and `asm` for service management.
  - [ ] `config set <name> <value>`
    - Update a config setting
- [x] `help [options] [command]`
  - Display help for a given command.
- [ ] `login [options] [username]`
  - Log in to an Azure subscription using Active Directory. 
  - Currently, the user can login only via Microsoft organizational account.
- [ ] `logout [options] [username]`
  - Log out from Azure subscription using Active Directory. 
  - Currently, the user can log out only via Microsoft organizational account
- [ ] `service`
  - [ ] `cert`
    - Manage your Cloud Services certificates
    - [ ] `list [options]`
    - [ ] `create [options] <dns-name> <file> [password]`
    - [ ] `delete [options] <thumbprint>`
  - [ ] `create [options] <serviceName>`
    - Create a cloud service.
  - [ ] `delete [options] <serviceName>`
    - Delete a cloud service.
  - [ ] `internal-load-balancer`
    - Manage internal load balancers for your Cloud Service Deployment
    - [ ] `add [options] [serviceName] [internalLBName]`
    - [ ] `delete [options] [serviceName] [internalLBName]`
    - [ ] `list [options] [serviceName]`
    - [ ] `set [options] [serviceName] [internalLBName]`
  - [ ] `list [options]`
    - List Azure cloud services.
  - [ ] `show [options] <serviceName>`
    - Show Azure cloud service.
  - [ ] `load-balanced-set`
    - Commands to manage load balanced set for a Cloud Service Deployment
    - [ ] `list [options] <serviceName>`
    - [ ] `set [options] <serviceName> <load-balanced-set-name>`
    - [ ] `show [options] <serviceName>`
- [ ] `storage` 
  - Manage your Storage objects
  - [ ] `account`
    - Manage your Storage accounts.
    - [ ] `check [options] <name>`
    - [ ] `create [options] <name>`
    - [ ] `connectionstring show [options] <name>`
    - [ ] `delete [options] <name>`
    - [ ] `keys`
      - Manage your Storage accounts keys.
      - [ ] `list [options] <name>`
      - [ ] `renew [options] <name>`
    - [ ] `list [options]`
    - [ ] `set [options] <name>`
    - [ ] `show [options] <name>`
  - [ ] `blob`
    - Manage your Storage blobs.
    - [ ] `copy`
      - Manage your blob copy operations.
      - [ ] `show [options] [container] [blob]`
      - [ ] `start [options] [sourceUri] [destContainer]`
      - [ ] `stop [options] [container] [blob] [copyid]`
    - [ ] `delete [options] [container] [blob]`
    - [ ] `download [options] [container] [blob] [destination]`
    - [ ] `list [options] [container] [prefix]`
    - [ ] `sas create [options] [container] [blob] [permissions] [expiry]`
    - [ ] `show [options] [container] [blob]`
    - [ ] `upload [options] [file] [container] [blob]`
  - [ ] `container`
    - Manage your Storage containers.
    - [ ] `create [options] [container]`
    - [ ] `delete [options] [container]`
    - [ ] `list [options] [prefix]`
    - [ ] `policy`
      - Manage stored access policies of your Storage container.
      - [ ] `create [options] [container] [name]`
      - [ ] `delete [options] [container] [name]` 
      - [ ] `list [options] [container]`
      - [ ] `set [options] [container] [name]`  
      - [ ] `show [options] [container] [name]`
    - [ ] `sas create [options] [container] [permissions] [expiry]`
    - [ ] `set [options] [container]`
    - [ ] `show [options] [container]`
  - [ ] `cors`
    - Manage your Storage CORS (Cross-Origin Resource Sharing).
    - [ ] `delete [options]`
    - [ ] `set [options]`
    - [ ] `show [options]`
  - [ ] `directory`
    - Manage your Storage file directory.
    - [ ] `create [options] [share] [path]`
    - [ ] `delete [options] [share] [path]`
  - [ ] `file`
    - Manage your Storage files.
    - [ ] `delete [options] [share] [path]`
    - [ ] `download [options] [share] [path] [destination]`
    - [ ] `copy`
      - Manage your file copy operations.
      - [ ] `show [options] [share] [path]`
      - [ ] `start [options] [sourceUri] [destShare]`
      - [ ] `stop [options] [share] [path] [copyid]`
    - [ ] `list [options] [share] [path]`
    - [ ] `sas create [options] [share] [path] [permissions] [expiry]`
    - [ ] `upload [options] [source] [share] [path]`
  - [ ] `logging`
    - Manage your Storage logging properties.
    - [ ] `set [options]`
    - [ ] `show [options]`
  - [ ] `metrics`
    - Manage your Storage metrics properties.
    - [ ] `set [options]`
    - [ ] `show [options]`
  - [ ] `queue`
    - Manage your Storage queues.
    - [ ] `create [options] [queue]`
    - [ ] `delete [options] [queue]`
    - [ ] `list [options] [prefix]`
    - [ ] `policy`
      - Manage stored access policies of your Storage queue.
      - [ ] `create [options] [container] [name]`
      - [ ] `delete [options] [container] [name]` 
      - [ ] `list [options] [container]`
      - [ ] `set [options] [container] [name]`  
      - [ ] `show [options] [container] [name]`
    - [ ] `sas create [options] [queue] [permissions] [expiry]`
    - [ ] `show [options] [queue]`
  - [ ] `share`
    - Manage your Storage file shares.
      - [ ] `create [options] [share]`
      - [ ] `delete [options] [share]`
      - [ ] `list [options] [prefix]`
      - [ ] `policy`
        - Manage stored access policies of your Storage file share.
        - `create [options] [share] [name]`
        - `delete [options] [share] [name]`
        - `list [options] [share]`
        - `set [options] [share] [name]`
        - `show [options] [share] [name]`
      - [ ] `sas create [options] [share] [permissions] [expiry]`
      - [ ] `set [options] [share]`
      - [ ] `show [options] [share]`
  - [ ] `table`
    - [ ] `create [options] [queue]`
    - [ ] `delete [options] [queue]`
    - [ ] `list [options] [prefix]`
    - [ ] `policy`
      - Manage stored access policies of your Storage table.
      - [ ] `create [options] [container] [name]`
      - [ ] `delete [options] [container] [name]` 
      - [ ] `list [options] [container]`
      - [ ] `set [options] [container] [name]`  
      - [ ] `show [options] [container] [name]`
    - [ ] `sas create [options] [share] [permissions] [expiry]`
    - [ ] `set [options] [queue]`
    - [ ] `show [options] [queue]`
